In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [2]:
# Load the dataset
data = pd.read_csv("House_Rent.csv")

In [3]:
# Split the data
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [4]:
# Preprocess the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
# Train the algorithms
classifiers = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "SVM": SVC(),
    "Naive Bayes": GaussianNB()
}

In [6]:
for name, classifier in classifiers.items():
    classifier.fit(X_train, y_train)
    y_pred1 = classifier.predict(X_test)
    y_pred2 = classifier.predict(X_test)
    y_pred3= classifier.predict(X_test)

    print(f"{name}:")
    print(f"Accuracy score: {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision score: {precision_score(y_test, y_pred, average='weighted'):.4f}")
    print(f"Recall score: {recall_score(y_test, y_pred, average='weighted'):.4f}")
    print(f"F1 score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
    print("\n")

# Choose the best algorithm based on the evaluation metrics

C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Logistic Regression:
Accuracy score: 0.7246
Precision score: 0.7114
Recall score: 0.7246
F1 score: 0.7149


Random Forest:
Accuracy score: 0.7295
Precision score: 0.7290
Recall score: 0.7295
F1 score: 0.7280


Decision Tree:
Accuracy score: 0.6843
Precision score: 0.6893
Recall score: 0.6843
F1 score: 0.6852


K-Nearest Neighbors:
Accuracy score: 0.7436
Precision score: 0.7353
Recall score: 0.7436
F1 score: 0.7376


SVM:
Accuracy score: 0.7182
Precision score: 0.7120
Recall score: 0.7182
F1 score: 0.7118


Naive Bayes:
Accuracy score: 0.4449
Precision score: 0.6521
Recall score: 0.4449
F1 score: 0.5004




C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [7]:
# Generate the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[298  27   1   0   0  95]
 [194 300  11   0   0 209]
 [  3  70  26   2   0 112]
 [  0   3  13   5   0  33]
 [  0   0   4   1   0   8]
 [  0   0   0   0   0   1]]
