In [98]:
#Rescale Data

In [99]:
# importing libraries
import pandas as pd
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler

In [100]:
# data set link
df=pd.read_csv("House_Rent.csv")

In [101]:
# data parameters
names = ['BHK', 'Rent', 'Size']

In [102]:
# preparating of dataframe using the data at given link and defined columns list
dataframe = pandas.read_csv("House_Rent.csv", names = names)
array = dataframe.values

In [103]:
# separate array into input and output components
X = array[:,0:8]
Y = array[:,2]

In [104]:
# initialising the MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(df[names])

MinMaxScaler()

In [105]:
df[names] = scaler.transform(df[names])

In [106]:
numpy.set_printoptions(precision=8)
print(X)

[['City' 'Furnishing Status' 'Bathroom']
 ['1' '1' '2']
 ['1' '2' '1']
 ...
 ['6' '2' '3']
 ['6' '2' '2']
 ['6' '1' '2']]


In [107]:
#Python code for binarization

In [108]:
# import libraries
from sklearn.preprocessing import Binarizer
import pandas
import numpy

In [109]:
# data set link
df=pd.read_csv("House_Rent.csv")

In [110]:
# data parameters
names = ['BHK', 'Rent', 'Size']

In [111]:
# preparating of dataframe using the data at given link and defined columns list
dataframe = pandas.read_csv("House_Rent.csv", names = names)
array = dataframe.values

In [131]:
# separate array into input and output components
X = array[:, 0:2]
Y = array[:, 2]
binarizer = Binarizer(threshold = 0.0).fit(X[1:])
binaryX = binarizer.transform(X[1:])

In [138]:
# separate array into input and output components
X = array[:, 0:7]
Y = array[:, 2]
binarizer = Binarizer(threshold = 0.0).fit(X[1:])
binaryX = binarizer.transform(X[1:])

In [141]:
# summarize transformed data
numpy.set_printoptions(precision = 7)
print(binaryX[0:8,0:8])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [142]:
#Standardize Data

In [149]:
# import libraries
from sklearn.preprocessing import StandardScaler
import pandas
import numpy

In [150]:
# data set link
df=pd.read_csv("House_Rent.csv")

In [151]:
# data parameters
names = ['BHK', 'Rent', 'Size']

In [152]:
# preparating of dataframe using the data at given link and defined columns list
dataframe = pandas.read_csv("House_Rent.csv", names = names)
array = dataframe.values

In [154]:
# separate array into input and output components
X = array[:, 0:2]
Y = array[:, 2]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

ValueError: could not convert string to float: 'City'